create table tabel1 (
	id INT,
	Nimi VARCHAR(50),
	Asukoht VARCHAR(50),
	Keskmine_hinne DECIMAL(3,1),
	Hinnatud INT
);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (1, 'Ooba', '83 Farragut Trail', 1.0, 651);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (2, 'Babblestorm', '1 Messerschmidt Court', 1.3, 46);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (3, 'Trudeo', '889 Springview Trail', 5.0, 194);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (4, 'JumpXS', '625 Amoth Hill', 9.7, 330);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (5, 'Muxo', '3307 Del Mar Drive', 4.4, 554);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (6, 'Topdrive', '1 Main Road', 5.5, 428);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (7, 'Ailane', '15 Loftsgordon Circle', 9.4, 381);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (8, 'Roomm', '5 Scott Alley', 5.3, 429);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (9, 'Oyope', '779 Holmberg Point', 7.6, 688);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (10, 'Dabjam', '12 Shasta Trail', 9.3, 284);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (11, 'Twitterlist', '71 Talisman Place', 1.7, 579);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (12, 'Skinte', '0231 Jenifer Parkway', 4.5, 596);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (13, 'Brainverse', '95 Texas Trail', 9.7, 548);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (14, 'Mydo', '01712 Forest Junction', 9.2, 616);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (15, 'Bluejam', '16778 Basil Trail', 9.9, 31);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (16, 'Skaboo', '06775 Darwin Center', 6.7, 943);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (17, 'Plambee', '106 Hoepker Drive', 2.6, 717);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (18, 'Shuffledrive', '76611 Grayhawk Crossing', 3.8, 11);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (19, 'Centimia', '18 Red Cloud Circle', 9.7, 686);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (20, 'Mymm', '11441 Browning Lane', 6.5, 196);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (21, 'Yabox', '725 Troy Point', 7.9, 438);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (22, 'Quaxo', '4 Harbort Crossing', 6.2, 335);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (23, 'Zoomcast', '86108 Huxley Point', 7.6, 707);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (24, 'Skipfire', '80206 Shasta Place', 6.7, 765);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (25, 'Thoughtsphere', '6 Maywood Lane', 4.6, 663);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (26, 'Rhyloo', '95 1st Point', 6.2, 55);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (27, 'Twinder', '43 Melby Place', 1.6, 580);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (28, 'Trilia', '59 Mosinee Drive', 8.2, 925);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (29, 'Ooba', '9197 Kim Street', 4.2, 845);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (30, 'Oyoloo', '45653 Fulton Parkway', 2.3, 554);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (31, 'Eabox', '93 Maple Street', 1.6, 468);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (32, 'Yozio', '8 7th Place', 7.2, 598);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (33, 'Browsebug', '304 Mccormick Center', 5.2, 201);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (34, 'Yozio', '242 Service Trail', 8.7, 277);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (35, 'Photobean', '244 Cardinal Terrace', 5.2, 35);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (36, 'Oyoloo', '53 Miller Court', 5.0, 350);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (37, 'Realcube', '026 Warbler Drive', 8.5, 227);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (38, 'Kwinu', '41062 Pearson Hill', 5.2, 311);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (39, 'Flashpoint', '2361 Lakewood Crossing', 7.5, 386);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (40, 'Linkbuzz', '55 Mayer Terrace', 3.3, 518);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (41, 'Mybuzz', '90 Graedel Trail', 4.3, 151);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (42, 'Skalith', '0824 Milwaukee Way', 7.0, 221);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (43, 'Tagopia', '5 Waxwing Park', 2.3, 732);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (44, 'Katz', '22 Lakewood Point', 2.9, 371);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (45, 'Yotz', '6173 Loftsgordon Street', 4.8, 763);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (46, 'Vimbo', '7 Lillian Park', 4.7, 742);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (47, 'Linklinks', '4671 Sauthoff Court', 9.5, 15);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (48, 'Ooba', '993 Sage Circle', 8.6, 564);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (49, 'Buzzbean', '9 Tennyson Crossing', 3.4, 168);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (50, 'Photobug', '8895 Kim Crossing', 5.0, 370);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (51, 'Devbug', '6615 Ludington Parkway', 3.2, 264);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (52, 'Skinix', '05064 Westend Parkway', 4.3, 698);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (53, 'Zoonder', '365 Jana Lane', 9.8, 696);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (54, 'Tagopia', '70525 Park Meadow Parkway', 6.1, 844);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (55, 'Mynte', '077 Kipling Hill', 5.0, 161);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (56, 'Trupe', '68313 Cascade Center', 7.1, 367);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (57, 'Thoughtsphere', '24 Hoepker Terrace', 1.9, 645);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (58, 'Devbug', '8044 Trailsway Circle', 9.8, 530);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (59, 'Quire', '8571 Rusk Court', 3.9, 138);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (60, 'Jazzy', '0 Heffernan Plaza', 9.3, 260);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (61, 'Photobean', '7 Hansons Road', 4.7, 220);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (62, 'Fadeo', '1335 Meadow Valley Center', 8.1, 982);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (63, 'Quinu', '1749 Stang Way', 6.5, 170);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (64, 'Wikido', '71721 Meadow Ridge Trail', 8.7, 283);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (65, 'Topdrive', '6 Pepper Wood Court', 3.1, 15);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (66, 'Meedoo', '000 Moose Trail', 4.1, 619);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (67, 'Jayo', '6 Marquette Hill', 9.1, 136);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (68, 'BlogXS', '35 Bashford Parkway', 1.4, 783);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (69, 'Zoomlounge', '4358 Anderson Road', 7.6, 926);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (70, 'Photobug', '5 Burning Wood Way', 7.5, 783);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (71, 'Trudoo', '73793 Melvin Plaza', 8.8, 588);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (72, 'Twitterbeat', '62597 Brickson Park Lane', 9.0, 130);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (73, 'Talane', '25 Dennis Road', 9.6, 245);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (74, 'Gigazoom', '46173 Mayfield Avenue', 3.8, 684);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (75, 'Eamia', '4 Erie Center', 7.6, 131);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (76, 'Feedmix', '22 David Park', 3.3, 893);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (77, 'Trudoo', '18 Mockingbird Place', 4.7, 132);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (78, 'Youspan', '9027 Hollow Ridge Place', 2.3, 761);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (79, 'Thoughtbeat', '34 Ridgeview Drive', 3.2, 279);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (80, 'Fivebridge', '65 Moose Circle', 1.2, 526);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (81, 'Jabberbean', '088 Dorton Court', 5.3, 346);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (82, 'Devpulse', '103 Veith Plaza', 1.0, 151);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (83, 'Rhyzio', '54 Division Road', 7.7, 603);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (84, 'Reallinks', '260 Menomonie Trail', 7.5, 259);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (85, 'Tagopia', '58791 Basil Terrace', 3.2, 403);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (86, 'Zoomlounge', '5 Ryan Parkway', 2.3, 91);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (87, 'Mynte', '3661 Sunnyside Parkway', 7.9, 826);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (88, 'Gabtype', '28645 Grover Plaza', 4.8, 248);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (89, 'Jabbersphere', '99 Rusk Place', 2.3, 540);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (90, 'Flashdog', '45021 Twin Pines Pass', 9.8, 93);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (91, 'Kaymbo', '5622 Shelley Avenue', 7.6, 835);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (92, 'Shuffledrive', '793 Crownhardt Lane', 1.5, 344);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (93, 'Meembee', '4551 Shelley Lane', 6.6, 163);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (94, 'Avavee', '63 Sheridan Drive', 1.2, 515);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (95, 'Meejo', '92709 Cordelia Street', 5.9, 918);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (96, 'Centizu', '2 Cherokee Trail', 8.7, 941);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (97, 'Camido', '2 Blackbird Crossing', 7.3, 730);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (98, 'Wikizz', '1835 Autumn Leaf Place', 7.5, 313);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (99, 'Thoughtstorm', '743 Di Loreto Alley', 7.7, 829);
insert into tabel1 (id, Nimi, Asukoht, Keskmine_hinne, Hinnatud) values (100, 'Shuffledrive', '54180 International Place', 2.5, 459);
