---
- name: Ping all hosts
  hosts: virtualmachines
  tasks:
    - name: Ping each host
      ping:

- name: Gather OS and kernel info
  hosts: virtualmachines
  gather_facts: yes
  tasks:
    - name: Get OS and kernel details
      debug:
        msg: "Hostname: {{ ansible_hostname }}, OS: {{ ansible_distribution }} {{ ansible_distribution_version }}, Kernel: {{ ansible_kernel }}"
